name: Code Linting and Commenting

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches: ["main"]
  push:
    types:
      - opened
      - synchronize
    branches: ["main"]


jobs:
  linting_and_commenting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8
      run: |
        flake8 --output-file lint_output.txt

    - name: Post linting comments
      run: |
        python comment_on_pr.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
