name: Code Linting and Commenting

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linting_and_commenting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8
      run: |
        flake8 --output-file lint_output.txt
        cat lint_output.txt
